# Generated by Django 5.0.3 on 2026-01-25 21:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PushNotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_ids', models.JSONField(help_text='Lista de player_ids a los que se envió', verbose_name='Player IDs')),
                ('notification_type', models.CharField(help_text='booking_created, booking_accepted, etc.', max_length=50, verbose_name='Tipo de Notificación')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('data', models.JSONField(blank=True, help_text='Data payload para la notificación', null=True, verbose_name='Datos Adicionales')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('sent', 'Enviado'), ('delivered', 'Entregado'), ('failed', 'Fallido')], default='pending', max_length=20, verbose_name='Estado')),
                ('onesignal_id', models.CharField(blank=True, help_text='ID de la notificación retornado por OneSignal', max_length=255, null=True, verbose_name='ID de OneSignal')),
                ('response', models.TextField(blank=True, null=True, verbose_name='Respuesta de API')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Mensaje de Error')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='push_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Notificación Push',
                'verbose_name_plural': 'Logs de Notificaciones Push',
                'db_table': 'push_notification_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='push_notifi_user_id_861605_idx'), models.Index(fields=['status'], name='push_notifi_status_9b0ff9_idx'), models.Index(fields=['notification_type'], name='push_notifi_notific_89bba9_idx')],
            },
        ),
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.CharField(help_text='ID único del dispositivo en OneSignal', max_length=255, unique=True, verbose_name='Player ID de OneSignal')),
                ('device_type', models.CharField(blank=True, help_text='Web, Android, iOS, etc.', max_length=50, verbose_name='Tipo de Dispositivo')),
                ('is_active', models.BooleanField(default=True, help_text='Desactivar si el usuario desuscribe', verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Suscripción Push',
                'verbose_name_plural': 'Suscripciones Push',
                'db_table': 'push_subscriptions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='push_subscr_user_id_c81a15_idx'), models.Index(fields=['player_id'], name='push_subscr_player__aef79b_idx')],
            },
        ),
    ]
