# Generated by Django 5.0.3 on 2025-11-02 19:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_systemconfig_providerzonecost'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(choices=[('pichincha', 'Banco Pichincha'), ('guayaquil', 'Banco Guayaquil'), ('pacifico', 'Banco del Pacífico'), ('produbanco', 'Produbanco'), ('internacional', 'Banco Internacional'), ('bolivariano', 'Banco Bolivariano'), ('austro', 'Banco del Austro'), ('other', 'Otro')], max_length=100, verbose_name='Banco')),
                ('account_type', models.CharField(choices=[('savings', 'Ahorro'), ('checking', 'Corriente')], max_length=20, verbose_name='Tipo de Cuenta')),
                ('account_number', models.CharField(max_length=50, verbose_name='Número de Cuenta')),
                ('account_holder', models.CharField(max_length=200, verbose_name='Titular')),
                ('id_number', models.CharField(max_length=20, verbose_name='RUC/Cédula')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('order', models.IntegerField(default=0, verbose_name='Orden')),
                ('notes', models.TextField(blank=True, help_text='Información adicional para el usuario', verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Cuenta Bancaria',
                'verbose_name_plural': 'Cuentas Bancarias',
                'db_table': 'bank_accounts',
                'ordering': ['order', 'bank_name'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('code', models.CharField(choices=[('payphone', 'PayPhone'), ('bank_transfer', 'Transferencia Bancaria'), ('credit_card', 'Tarjeta de Crédito'), ('cash', 'Efectivo')], max_length=50, unique=True, verbose_name='Código')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('icon', models.CharField(default='fa-credit-card', max_length=50, verbose_name='Icono (Font Awesome)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('order', models.IntegerField(default=0, verbose_name='Orden')),
                ('requires_proof', models.BooleanField(default=False, help_text='Si requiere subir imagen de comprobante', verbose_name='Requiere Comprobante')),
                ('requires_reference', models.BooleanField(default=False, help_text='Si requiere código/número de referencia', verbose_name='Requiere Referencia')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Método de Pago',
                'verbose_name_plural': 'Métodos de Pago',
                'db_table': 'payment_methods',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PaymentProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_code', models.CharField(blank=True, max_length=100, verbose_name='Código de Referencia')),
                ('proof_image', models.ImageField(blank=True, null=True, upload_to='payment_proofs/', verbose_name='Imagen del Comprobante')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('verified', models.BooleanField(default=False, verbose_name='Verificado')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Verificación')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.bankaccount', verbose_name='Cuenta Bancaria')),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_proof', to='core.booking', verbose_name='Reserva')),
                ('payment_method', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.paymentmethod', verbose_name='Método de Pago')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_payments', to=settings.AUTH_USER_MODEL, verbose_name='Verificado por')),
            ],
            options={
                'verbose_name': 'Comprobante de Pago',
                'verbose_name_plural': 'Comprobantes de Pago',
                'db_table': 'payment_proofs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('booking_created', 'Nueva Reserva'), ('booking_accepted', 'Reserva Aceptada'), ('booking_rejected', 'Reserva Rechazada'), ('booking_completed', 'Reserva Completada'), ('payment_received', 'Pago Recibido'), ('payment_verified', 'Pago Verificado'), ('review_received', 'Nueva Reseña'), ('system', 'Sistema')], max_length=50, verbose_name='Tipo')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('action_url', models.CharField(blank=True, max_length=500, verbose_name='URL de Acción')),
                ('is_read', models.BooleanField(default=False, verbose_name='Leída')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Leída el')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.booking', verbose_name='Reserva')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='notificatio_user_id_a4dd5c_idx'), models.Index(fields=['-created_at'], name='notificatio_created_8fa075_idx')],
            },
        ),
    ]
