# Generated by Django 5.0.3 on 2025-11-04 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_providerprofile_business_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerprofile',
            name='id_card_back',
            field=models.ImageField(blank=True, max_length=255, upload_to='documents/', verbose_name='Cédula posterior'),
        ),
        migrations.AlterField(
            model_name='providerprofile',
            name='id_card_front',
            field=models.ImageField(blank=True, max_length=255, upload_to='documents/', verbose_name='Cédula frontal'),
        ),
        migrations.AlterField(
            model_name='providerprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, help_text='Foto de perfil (puede ser comercial)', max_length=255, upload_to='profiles/', verbose_name='Foto de Perfil'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, max_length=255, upload_to='services/', verbose_name='Imagen'),
        ),
    ]
