# Generated by Django 5.0.3 on 2025-11-06 03:11

import core.custom_fields
import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_providerprofile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerprofile',
            name='documents_verified',
            field=models.BooleanField(default=False, help_text='Indica si los documentos han sido validados por admin', verbose_name='Documentos Verificados'),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='documents_verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Documentos Verificados En'),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='selfie_with_id',
            field=core.custom_fields.SmartImageField(blank=True, help_text='Foto del rostro sosteniendo la cédula de identidad', max_length=255, null=True, upload_to='providers/validation/selfie/', validators=[core.validators.validate_image_size_2mb], verbose_name='Foto Rostro con Cédula'),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL amigable del perfil', unique=True, verbose_name='Slug'),
        ),
    ]
