# Generated by Django 5.0.3 on 2025-11-06 22:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_providerprofile_documents_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerprofile',
            name='registration_step',
            field=models.IntegerField(default=1, help_text='1: Datos básicos, 2: Verificación identidad, 3: Completo', verbose_name='Paso de Registro'),
        ),
        migrations.AddField(
            model_name='service',
            name='service_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único del servicio', unique=True, verbose_name='Código de Servicio'),
        ),
    ]
