# Generated by Django 5.0.3 on 2025-11-08 22:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_booking_service_booking_sub_total_cost_booking_tax_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderBankAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bank_name', models.CharField(max_length=128, verbose_name='Banco')),
                ('account_type', models.CharField(choices=[('checking', 'Cuenta Corriente'), ('savings', 'Cuenta de Ahorros')], max_length=64, verbose_name='Tipo de Cuenta')),
                ('country', models.CharField(default='EC', max_length=64, verbose_name='País')),
                ('account_number_masked', models.CharField(max_length=64, verbose_name='Número Enmascarado')),
                ('account_number_encrypted', models.TextField(blank=True, null=True, verbose_name='Número Cifrado')),
                ('owner_fullname', models.CharField(max_length=200, verbose_name='Titular')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Principal')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_bank_accounts', to=settings.AUTH_USER_MODEL, verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Cuenta Bancaria del Proveedor',
                'verbose_name_plural': 'Cuentas Bancarias de Proveedores',
                'db_table': 'provider_bank_accounts',
                'unique_together': {('provider', 'account_number_masked')},
            },
        ),
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requested_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Solicitado')),
                ('commission_percent', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='% Comisión')),
                ('commission_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Comisión')),
                ('amount_payable', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto a Pagar')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('rejected', 'Rechazado'), ('completed', 'Completado')], default='pending', max_length=20, verbose_name='Estado')),
                ('admin_note', models.TextField(blank=True, verbose_name='Nota Admin')),
                ('transfer_receipt_number', models.CharField(blank=True, max_length=256, verbose_name='Nº Comprobante')),
                ('covered_bookings', models.JSONField(blank=True, default=list, verbose_name='Reservas Cubiertas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_withdrawals', to=settings.AUTH_USER_MODEL, verbose_name='Procesado Por')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_requests', to=settings.AUTH_USER_MODEL, verbose_name='Proveedor')),
                ('provider_bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.providerbankaccount', verbose_name='Cuenta Bancaria')),
            ],
            options={
                'verbose_name': 'Solicitud de Retiro',
                'verbose_name_plural': 'Solicitudes de Retiro',
                'db_table': 'withdrawal_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
