# Generated by Django 5.0.3 on 2025-11-08 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_providerbankaccount_withdrawalrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Nombre')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('country', models.CharField(default='EC', max_length=64, verbose_name='País')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
            ],
            options={
                'verbose_name': 'Banco',
                'verbose_name_plural': 'Bancos',
                'db_table': 'banks',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='providerbankaccount',
            name='bank_name',
        ),
        migrations.AddField(
            model_name='providerbankaccount',
            name='bank',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='core.bank', verbose_name='Banco'),
            preserve_default=False,
        ),
    ]
