# Generated by Django 5.0.3 on 2025-11-09 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_bank_remove_providerbankaccount_bank_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerificationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email a Verificar')),
                ('token', models.CharField(max_length=255, unique=True, verbose_name='Token')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Verificado en')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Verificado')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_verification_token', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Token de Verificación de Email',
                'verbose_name_plural': 'Tokens de Verificación de Email',
                'db_table': 'email_verification_tokens',
            },
        ),
    ]
