# Generated by Django 5.0.3 on 2025-11-18 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_profile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='completion_code',
            field=models.CharField(blank=True, help_text='Código de 6 dígitos que el cliente entrega al proveedor', max_length=6, null=True, verbose_name='Código de Finalización'),
        ),
        migrations.AddField(
            model_name='booking',
            name='incident_description',
            field=models.TextField(blank=True, help_text='Detalles del problema reportado por el cliente', null=True, verbose_name='Descripción de Incidencia'),
        ),
        migrations.AddField(
            model_name='booking',
            name='incident_reported',
            field=models.BooleanField(default=False, help_text='Si el cliente reportó que no recibió el servicio', verbose_name='Incidencia Reportada'),
        ),
        migrations.AddField(
            model_name='booking',
            name='incident_reported_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Incidencia Reportada En'),
        ),
    ]
