# Generated by Django 5.0.3 on 2025-11-18 04:25
# FIXED VERSION 2 - Usando Python en lugar de SQL directo

import django.db.models.deletion
from django.db import migrations, models


def create_cities_from_zones(apps, schema_editor):
    """
    Crea registros City basados en los valores únicos de Zone.city
    """
    Zone = apps.get_model('core', 'Zone')
    City = apps.get_model('core', 'City')
    
    # Obtener valores únicos de city en Zone
    zone_cities = Zone.objects.values_list('city', flat=True).distinct()
    
    # Definir mapeo de ciudades a códigos
    city_mapping = {
        'Quito': 'QTO',
        'Guayaquil': 'GYE',
        'Cuenca': 'CUI',
    }
    
    # Crear ciudades si no existen
    for city_name in zone_cities:
        if city_name:  # Ignorar valores NULL o vacíos
            code = city_mapping.get(city_name, city_name[:3].upper())
            City.objects.get_or_create(
                name=city_name,
                defaults={
                    'code': code,
                    'country': 'Ecuador',
                    'active': True,
                    'display_order': 0,
                }
            )


def migrate_zone_cities(apps, schema_editor):
    """
    Mapea datos del campo city (CharField) al nuevo city_new (ForeignKey)
    """
    Zone = apps.get_model('core', 'Zone')
    City = apps.get_model('core', 'City')
    
    # Procesar cada zona
    for zone in Zone.objects.filter(city__isnull=False).exclude(city=''):
        try:
            city_obj = City.objects.get(name=zone.city)
            zone.city_new = city_obj
            zone.save()
        except City.DoesNotExist:
            # Si no existe la ciudad, intentar crear una
            code = zone.city[:3].upper() if zone.city else 'XXX'
            city_obj, _ = City.objects.get_or_create(
                name=zone.city,
                defaults={'code': code}
            )
            zone.city_new = city_obj
            zone.save()


def reverse_migrate_cities(apps, schema_editor):
    """Reverse no hace nada"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_booking_slug'),
    ]

    operations = [
        # Paso 1: Crear modelo City
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('code', models.CharField(help_text='Ej: QTO, GYE, CUI', max_length=10, unique=True, verbose_name='Código')),
                ('country', models.CharField(default='Ecuador', max_length=100, verbose_name='País')),
                ('active', models.BooleanField(default=True, verbose_name='Activa')),
                ('display_order', models.IntegerField(default=0, verbose_name='Orden de visualización')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Ciudad',
                'verbose_name_plural': 'Ciudades',
                'db_table': 'cities',
                'ordering': ['display_order', 'name'],
            },
        ),
        
        # Paso 2: Agregar campos ForeignKey a Location y Profile
        migrations.AddField(
            model_name='location',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='core.city', verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='profile',
            name='current_city',
            field=models.ForeignKey(blank=True, help_text='La ciudad donde el usuario está buscando servicios', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_current', to='core.city', verbose_name='Ciudad Actual'),
        ),
        
        # Paso 3: Agregar campo city_new a Zone (ForeignKey temporal)
        migrations.AddField(
            model_name='zone',
            name='city_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zones_temp', to='core.city', verbose_name='Ciudad'),
        ),
        
        # Paso 4: Crear ciudades desde los valores existentes
        migrations.RunPython(create_cities_from_zones, reverse_migrate_cities),
        
        # Paso 5: Migrar datos de city (CharField) a city_new (ForeignKey)
        migrations.RunPython(migrate_zone_cities, reverse_migrate_cities),
        
        # Paso 6: Remover el campo antiguo city
        migrations.RemoveField(
            model_name='zone',
            name='city',
        ),
        
        # Paso 7: Renombrar city_new a city
        migrations.RenameField(
            model_name='zone',
            old_name='city_new',
            new_name='city',
        ),
        
        # Paso 8: Hacer city no-nullable y establecer related_name correcto
        migrations.AlterField(
            model_name='zone',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='core.city', verbose_name='Ciudad'),
        ),
        
        # Paso 9: Actualizar opciones de Zone
        migrations.AlterModelOptions(
            name='zone',
            options={'ordering': ['city__name', 'name'], 'verbose_name': 'Zona', 'verbose_name_plural': 'Zonas'},
        ),
        
        # Paso 10: Agregar unique_together
        migrations.AlterUniqueTogether(
            name='zone',
            unique_together={('name', 'city')},
        ),
    ]