# Generated by Django 5.0.3 on 2025-11-19 05:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_city_alter_zone_options_location_city_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True, verbose_name='Token')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Usado en')),
                ('is_used', models.BooleanField(default=False, verbose_name='Usado')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_token', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Token de Reset de Contraseña',
                'verbose_name_plural': 'Tokens de Reset de Contraseña',
                'db_table': 'password_reset_tokens',
            },
        ),
    ]
