# Generated by Django 5.0.3 on 2025-11-25 05:00

import core.custom_fields
import core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_location_recipient_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='providerprofile',
            name='service_mode',
            field=models.CharField(choices=[('home', 'Solo a domicilio'), ('local', 'Solo en local'), ('both', 'En local y a domicilio')], default='home', help_text='¿Atiende en domicilio, local, o ambos?', max_length=10, verbose_name='Modalidad de atención'),
        ),
        migrations.AlterField(
            model_name='paymentproof',
            name='proof_image',
            field=core.custom_fields.SmartImageField(blank=True, help_text='Imagen o foto del comprobante de pago', max_length=256, null=True, upload_to='payment_proofs/', validators=[core.validators.validate_image_size_5mb], verbose_name='Comprobante de Pago'),
        ),
        migrations.AlterField(
            model_name='providerprofile',
            name='id_card_back',
            field=core.custom_fields.SmartImageField(blank=True, max_length=255, upload_to='documents/', validators=[core.validators.validate_image_size_5mb], verbose_name='Cédula posterior'),
        ),
        migrations.AlterField(
            model_name='providerprofile',
            name='id_card_front',
            field=core.custom_fields.SmartImageField(blank=True, max_length=255, upload_to='documents/', validators=[core.validators.validate_image_size_5mb], verbose_name='Cédula frontal'),
        ),
        migrations.AlterField(
            model_name='providerprofile',
            name='profile_photo',
            field=core.custom_fields.SmartImageField(blank=True, help_text='Foto de perfil (puede ser comercial)', max_length=255, upload_to='profiles/', validators=[core.validators.validate_image_size_5mb], verbose_name='Foto de Perfil'),
        ),
        migrations.AlterField(
            model_name='providerprofile',
            name='selfie_with_id',
            field=core.custom_fields.SmartImageField(blank=True, help_text='Foto del rostro sosteniendo la cédula de identidad', max_length=255, null=True, upload_to='providers/validation/selfie/', validators=[core.validators.validate_image_size_5mb], verbose_name='Foto Rostro con Cédula'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=core.custom_fields.SmartImageField(blank=True, max_length=255, upload_to='services/', validators=[core.validators.validate_image_size_5mb], verbose_name='Imagen'),
        ),
        migrations.CreateModel(
            name='ProviderLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_type', models.CharField(choices=[('base', 'Domicilio base del proveedor'), ('local', 'Local / Sucursal del proveedor')], max_length=10, verbose_name='Tipo de ubicación')),
                ('label', models.CharField(help_text='Ej: Domicilio, Sucursal Norte, Oficina Centro', max_length=100, verbose_name='Nombre de la ubicación')),
                ('address', models.TextField(verbose_name='Dirección completa')),
                ('reference', models.CharField(blank=True, help_text='Ej: Frente a farmacia, Pasaje interno', max_length=255, verbose_name='Referencia adicional')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitud')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitud')),
                ('whatsapp_number', models.CharField(blank=True, help_text='Opcional: número específico para notificaciones', max_length=13, validators=[core.validators.validate_ecuador_phone], verbose_name='Número de WhatsApp para esta ubicación')),
                ('document_proof', core.custom_fields.SmartImageField(blank=True, help_text='Para locales: foto de pago de servicio básico', null=True, upload_to='provider_locations/docs/', validators=[core.validators.validate_image_size_5mb], verbose_name='Comprobante de servicios básicos')),
                ('is_verified', models.BooleanField(default=False, help_text='Solo locales verificados pueden recibir bookings', verbose_name='Verificada por admin')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.city', verbose_name='Ciudad')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_locations', to=settings.AUTH_USER_MODEL, verbose_name='Proveedor')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.zone', verbose_name='Zona')),
            ],
            options={
                'verbose_name': 'Ubicación de proveedor',
                'verbose_name_plural': 'Ubicaciones de proveedores',
                'db_table': 'provider_locations',
                'ordering': ['location_type', 'label'],
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='provider_location',
            field=models.ForeignKey(blank=True, help_text='Dónde se realizará el servicio', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='core.providerlocation', verbose_name='Ubicación del proveedor'),
        ),
        migrations.AddIndex(
            model_name='providerlocation',
            index=models.Index(fields=['provider', 'city', 'location_type'], name='provider_lo_provide_c7f854_idx'),
        ),
    ]
