# Generated by Django 5.0.3 on 2025-11-13 04:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('terms_user', 'Términos de Uso - Usuario'), ('privacy_user', 'Política de Privacidad - Usuario'), ('terms_provider', 'Términos de Uso - Proveedor'), ('privacy_provider', 'Política de Privacidad - Proveedor')], max_length=50, unique=True, verbose_name='Tipo de Documento')),
                ('version', models.IntegerField(default=1, verbose_name='Versión')),
                ('content', models.TextField(verbose_name='Contenido HTML')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('published', 'Publicado'), ('archived', 'Archivado')], default='draft', max_length=20, verbose_name='Estado')),
                ('is_active', models.BooleanField(default=False, help_text='Solo puede haber una versión activa por tipo de documento', verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_legal_documents', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Documento Legal',
                'verbose_name_plural': 'Documentos Legales',
                'db_table': 'legal_documents',
                'ordering': ['-created_at'],
                'unique_together': {('document_type', 'version')},
            },
        ),
        migrations.CreateModel(
            name='LegalAcceptance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted_at', models.DateTimeField(auto_now_add=True, verbose_name='Aceptado el')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP desde donde se aceptó el documento', null=True, verbose_name='Dirección IP')),
                ('user_agent', models.TextField(blank=True, help_text='Información del navegador/dispositivo', verbose_name='User Agent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_acceptances', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acceptances', to='legal.legaldocument', verbose_name='Documento')),
            ],
            options={
                'verbose_name': 'Aceptación Legal',
                'verbose_name_plural': 'Aceptaciones Legales',
                'db_table': 'legal_acceptances',
                'ordering': ['-accepted_at'],
                'unique_together': {('user', 'document')},
            },
        ),
    ]
