# Generated by Django 5.0.3 on 2025-11-19 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalacceptance',
            name='accepted_via',
            field=models.CharField(default='web_form', help_text='Método de aceptación: web_form, google_oauth, etc.', max_length=50, verbose_name='Aceptado vía'),
        ),
    ]
