# Generated by Django 5.0.3 on 2025-11-20 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsapplog',
            name='template_variables',
            field=models.JSONField(blank=True, help_text='Variables enviadas al template para permitir reintentos exactos', null=True, verbose_name='Variables del Template'),
        ),
    ]
