# Generated by Django 5.0.3 on 2025-11-02 02:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_zone_providerprofile_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='Clave')),
                ('value', models.TextField(verbose_name='Valor')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('value_type', models.CharField(choices=[('string', 'Texto'), ('integer', 'Número Entero'), ('decimal', 'Número Decimal'), ('boolean', 'Verdadero/Falso')], default='string', max_length=20, verbose_name='Tipo de Valor')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Configuración del Sistema',
                'verbose_name_plural': 'Configuraciones del Sistema',
                'db_table': 'system_config',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='ProviderZoneCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travel_cost', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Costo de traslado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone_costs', to=settings.AUTH_USER_MODEL, verbose_name='Proveedor')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.zone', verbose_name='Zona')),
            ],
            options={
                'verbose_name': 'Costo de Zona',
                'verbose_name_plural': 'Costos por Zona',
                'db_table': 'provider_zone_costs',
                'ordering': ['provider', 'zone'],
                'unique_together': {('provider', 'zone')},
            },
        ),
    ]
