# Generated by Django 5.0.3 on 2025-11-02 20:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_bankaccount_paymentmethod_paymentproof_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankaccount',
            options={'ordering': ['display_order', 'bank_name'], 'verbose_name': 'Cuenta Bancaria', 'verbose_name_plural': 'Cuentas Bancarias'},
        ),
        migrations.AlterModelOptions(
            name='paymentmethod',
            options={'ordering': ['display_order', 'name'], 'verbose_name': 'Método de Pago', 'verbose_name_plural': 'Métodos de Pago'},
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='core_notifi_user_id_cb8f07_idx',
            old_name='notificatio_user_id_a4dd5c_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='core_notifi_created_f19d5e_idx',
            old_name='notificatio_created_8fa075_idx',
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='id_number',
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='order',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='read_at',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='order',
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='display_order',
            field=models.IntegerField(default=0, help_text='Orden en que aparecerá en la lista (menor número = primero)', verbose_name='Orden de Visualización'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='identification',
            field=models.CharField(blank=True, help_text='RUC o cédula del titular', max_length=20, null=True, verbose_name='RUC/CI'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='display_order',
            field=models.IntegerField(default=0, help_text='Orden en que aparecerá en la lista (menor número = primero)', verbose_name='Orden de Visualización'),
        ),
        migrations.AddField(
            model_name='paymentproof',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='account_holder',
            field=models.CharField(help_text='Nombre completo o razón social del titular', max_length=200, verbose_name='Titular de la Cuenta'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='account_type',
            field=models.CharField(choices=[('savings', 'Ahorros'), ('checking', 'Corriente')], max_length=20, verbose_name='Tipo de Cuenta'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='bank_name',
            field=models.CharField(help_text='Ej: Banco Pichincha, Banco Guayaquil', max_length=100, verbose_name='Nombre del Banco'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Activar/Desactivar esta cuenta bancaria', verbose_name='Activa'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='notes',
            field=models.TextField(blank=True, help_text='Información adicional que verá el usuario (ej: horarios de transferencia)', null=True, verbose_name='Notas para el Usuario'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='action_url',
            field=models.CharField(blank=True, help_text='URL a la que se redirigirá al hacer clic en la notificación', max_length=500, null=True, verbose_name='URL de Acción'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.booking', verbose_name='Reserva Relacionada'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('booking_created', 'Nueva Reserva'), ('booking_accepted', 'Reserva Aceptada'), ('booking_rejected', 'Reserva Rechazada'), ('booking_completed', 'Reserva Completada'), ('payment_received', 'Pago Recibido'), ('payment_verified', 'Pago Verificado'), ('review_received', 'Nueva Reseña'), ('system', 'Notificación del Sistema')], max_length=50, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='code',
            field=models.CharField(help_text='Código único para identificar el método (ej: payphone, bank_transfer)', max_length=50, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='description',
            field=models.TextField(blank=True, help_text='Descripción que verá el usuario', null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='icon',
            field=models.CharField(blank=True, help_text='Emoji o código de ícono (ej: 💳, 🏦)', max_length=50, null=True, verbose_name='Ícono'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Activar/Desactivar este método de pago', verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre del Método'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='requires_proof',
            field=models.BooleanField(default=False, help_text='¿Este método requiere que el usuario suba una imagen de comprobante?', verbose_name='Requiere Comprobante'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='requires_reference',
            field=models.BooleanField(default=False, help_text='¿Este método requiere un código de referencia o número de transacción?', verbose_name='Requiere Referencia'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='paymentproof',
            name='bank_account',
            field=models.ForeignKey(blank=True, help_text='Cuenta bancaria a la que se realizó la transferencia', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.bankaccount', verbose_name='Cuenta Bancaria'),
        ),
        migrations.AlterField(
            model_name='paymentproof',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_proofs', to='core.booking', verbose_name='Reserva'),
        ),
        migrations.AlterField(
            model_name='paymentproof',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='paymentproof',
            name='notes',
            field=models.TextField(blank=True, help_text='Notas internas del administrador sobre este pago', null=True, verbose_name='Notas del Admin'),
        ),
        migrations.AlterField(
            model_name='paymentproof',
            name='payment_method',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='core.paymentmethod', verbose_name='Método de Pago'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paymentproof',
            name='proof_image',
            field=models.ImageField(blank=True, help_text='Imagen o foto del comprobante de pago', null=True, upload_to='payment_proofs/', verbose_name='Comprobante de Pago'),
        ),
        migrations.AlterField(
            model_name='paymentproof',
            name='reference_code',
            field=models.CharField(blank=True, help_text='Número de comprobante o referencia de la transacción', max_length=100, null=True, verbose_name='Código de Referencia'),
        ),
        migrations.AlterField(
            model_name='paymentproof',
            name='verified',
            field=models.BooleanField(default=False, help_text='¿El pago ha sido verificado por un administrador?', verbose_name='Verificado'),
        ),
        migrations.AlterField(
            model_name='paymentproof',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_payments', to=settings.AUTH_USER_MODEL, verbose_name='Verificado Por'),
        ),
        migrations.AddIndex(
            model_name='paymentproof',
            index=models.Index(fields=['booking', 'verified'], name='core_paymen_booking_dc2634_idx'),
        ),
        migrations.AlterModelTable(
            name='bankaccount',
            table=None,
        ),
        migrations.AlterModelTable(
            name='notification',
            table=None,
        ),
        migrations.AlterModelTable(
            name='paymentmethod',
            table=None,
        ),
        migrations.AlterModelTable(
            name='paymentproof',
            table=None,
        ),
    ]
