# Generated by Django 5.0.3 on 2025-11-03 01:10

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_bankaccount_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccount',
            name='identification',
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='bank_code',
            field=models.CharField(blank=True, help_text='Código identificador del banco', max_length=10, null=True, verbose_name='Código del Banco'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='id_number',
            field=models.CharField(default='0', help_text='Número de identificación del titular (RUC o Cédula)', max_length=20, validators=[django.core.validators.RegexValidator(message='Ingrese un número de cédula o RUC válido (10-13 dígitos)', regex='^\\d{10,13}$')], verbose_name='RUC/Cédula'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='swift_code',
            field=models.CharField(blank=True, help_text='Código internacional del banco (opcional)', max_length=20, null=True, verbose_name='Código SWIFT/BIC'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='account_number',
            field=models.CharField(help_text='Número de cuenta bancaria', max_length=50, unique=True, verbose_name='Número de Cuenta'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='account_type',
            field=models.CharField(choices=[('savings', 'Cuenta de Ahorros'), ('checking', 'Cuenta Corriente')], default='checking', max_length=20, verbose_name='Tipo de Cuenta'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='display_order',
            field=models.IntegerField(default=0, help_text='Orden en que se muestra (menor número = primero)', verbose_name='Orden de Visualización'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Si está activa, se mostrará a los clientes para realizar transferencias', verbose_name='Activa'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='notes',
            field=models.TextField(blank=True, help_text='Notas internas sobre esta cuenta (no visible para clientes)', null=True, verbose_name='Notas'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('pending_validation', 'Pendiente de Validación'), ('paid', 'Pagado'), ('refunded', 'Reembolsado')], default='pending', max_length=20, verbose_name='Estado de pago'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Monto del pago', max_digits=10)),
                ('payment_method', models.CharField(choices=[('payphone', 'PayPhone'), ('bank_transfer', 'Transferencia Bancaria'), ('cash', 'Efectivo')], default='payphone', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('pending_validation', 'Pendiente de Validación'), ('completed', 'Completado'), ('failed', 'Fallido'), ('refunded', 'Reembolsado'), ('cancelled', 'Cancelado')], default='pending', max_length=20)),
                ('transaction_id', models.CharField(blank=True, help_text='ID de transacción del procesador de pagos', max_length=100, null=True)),
                ('reference_number', models.CharField(blank=True, help_text='Número de referencia de la transferencia', max_length=100, null=True)),
                ('transfer_date', models.DateField(blank=True, help_text='Fecha en que se realizó la transferencia', null=True)),
                ('transfer_receipt', models.FileField(blank=True, help_text='Comprobante de la transferencia', null=True, upload_to='payment_receipts/')),
                ('notes', models.TextField(blank=True, help_text='Notas adicionales sobre el pago', null=True)),
                ('validated_at', models.DateTimeField(blank=True, help_text='Fecha y hora de validación', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.booking')),
                ('validated_by', models.ForeignKey(blank=True, help_text='Administrador que validó el pago', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-created_at'],
            },
        ),
    ]
