# Generated by Django 5.0.3 on 2025-11-04 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_bankaccount_identification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerprofile',
            name='business_name',
            field=models.CharField(blank=True, help_text='Nombre con el que se promociona el negocio', max_length=200, verbose_name='Nombre Comercial'),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, help_text='Foto de perfil (puede ser comercial)', upload_to='profiles/', verbose_name='Foto de Perfil'),
        ),
        migrations.AlterField(
            model_name='providerprofile',
            name='coverage_zones',
            field=models.ManyToManyField(blank=True, related_name='providers', to='core.zone', verbose_name='Zonas de cobertura'),
        ),
    ]
