# Generated by Django 5.0.3 on 2025-11-04 21:25

import core.custom_fields
import core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_providerprofile_id_card_back_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='transfer_receipt',
            field=core.custom_fields.SmartFileField(blank=True, help_text='Comprobante de la transferencia', null=True, upload_to='payment_receipts/'),
        ),
        migrations.AlterField(
            model_name='paymentproof',
            name='proof_image',
            field=core.custom_fields.SmartImageField(blank=True, help_text='Imagen o foto del comprobante de pago', max_length=256, null=True, upload_to='payment_proofs/', validators=[core.validators.validate_image_size_2mb], verbose_name='Comprobante de Pago'),
        ),
        migrations.AlterField(
            model_name='providerprofile',
            name='id_card_back',
            field=core.custom_fields.SmartImageField(blank=True, max_length=255, upload_to='documents/', validators=[core.validators.validate_image_size_2mb], verbose_name='Cédula posterior'),
        ),
        migrations.AlterField(
            model_name='providerprofile',
            name='id_card_front',
            field=core.custom_fields.SmartImageField(blank=True, max_length=255, upload_to='documents/', validators=[core.validators.validate_image_size_2mb], verbose_name='Cédula frontal'),
        ),
        migrations.AlterField(
            model_name='providerprofile',
            name='profile_photo',
            field=core.custom_fields.SmartImageField(blank=True, help_text='Foto de perfil (puede ser comercial)', max_length=255, upload_to='profiles/', validators=[core.validators.validate_image_size_2mb], verbose_name='Foto de Perfil'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=core.custom_fields.SmartImageField(blank=True, max_length=255, upload_to='services/', validators=[core.validators.validate_image_size_2mb], verbose_name='Imagen'),
        ),
    ]
