# Generated by Django 5.0.3 on 2025-11-05 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_payment_transfer_receipt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerprofile',
            name='status',
            field=models.CharField(choices=[('created', 'Creado'), ('pending', 'Pendiente'), ('approved', 'Aprobado'), ('rejected', 'Rechazado')], default='pending', max_length=10, verbose_name='Estado'),
        ),
    ]
