# Generated by Django 5.0.3 on 2025-11-07 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_providerprofile_registration_step_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='service',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Costo del servicio'),
        ),
        migrations.AddField(
            model_name='booking',
            name='sub_total_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Subtotal'),
        ),
        migrations.AddField(
            model_name='booking',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Impuesto / IVA'),
        ),
        migrations.AddField(
            model_name='booking',
            name='travel_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Costo de movilizacion'),
        ),
    ]
