# Generated by Django 5.0.3 on 2025-11-13 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_emailverificationtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='customer_completed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp cuando el cliente marca como completado', null=True, verbose_name='Completado por Cliente'),
        ),
        migrations.AddField(
            model_name='booking',
            name='provider_completed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp cuando el proveedor marca como completado', null=True, verbose_name='Completado por Proveedor'),
        ),
    ]
