# Generated by Django 5.0.3 on 2025-11-13 22:23

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_booking_customer_completed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(error_messages={'unique': 'Ya existe una cuenta registrada con este número de teléfono.'}, help_text='Número celular de Ecuador (09XXXXXXXX)', max_length=13, unique=True, validators=[core.validators.validate_ecuador_phone], verbose_name='Teléfono Celular'),
        ),
    ]
