# Generated by Django 5.0.3 on 2025-11-18 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_booking_completion_code_booking_incident_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='slug',
            field=models.SlugField(blank=True, help_text='Identificador único corto para la reserva', max_length=12, verbose_name='ID Corto (Slug)'),
        ),
    ]
