# Generated by Django 5.0.3 on 2025-11-19 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='recipient_name',
            field=models.CharField(blank=True, help_text='Nombre de la persona que recibirá el servicio en esta ubicación', max_length=200, verbose_name='Quién recibe el servicio'),
        ),
    ]
