# Generated by Django 5.0.3 on 2025-11-30 23:39

import apps.core.custom_fields
import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_providerprofile_service_mode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='transfer_receipt',
            field=apps.core.custom_fields.SmartFileField(blank=True, help_text='Comprobante de la transferencia', null=True, upload_to='payment_receipts/'),
        ),
        migrations.AlterField(
            model_name='paymentproof',
            name='proof_image',
            field=apps.core.custom_fields.SmartImageField(blank=True, help_text='Imagen o foto del comprobante de pago', max_length=256, null=True, upload_to='payment_proofs/', validators=[apps.core.validators.validate_image_size_5mb], verbose_name='Comprobante de Pago'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, error_messages={'unique': 'Ya existe una cuenta registrada con este número de teléfono.'}, help_text='Número celular de Ecuador (09XXXXXXXX)', max_length=13, null=True, unique=True, validators=[apps.core.validators.validate_ecuador_phone], verbose_name='Teléfono Celular'),
        ),
        migrations.AlterField(
            model_name='providerlocation',
            name='document_proof',
            field=apps.core.custom_fields.SmartImageField(blank=True, help_text='Para locales: foto de pago de servicio básico', null=True, upload_to='provider_locations/docs/', validators=[apps.core.validators.validate_image_size_5mb], verbose_name='Comprobante de servicios básicos'),
        ),
        migrations.AlterField(
            model_name='providerlocation',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='Opcional: número específico para notificaciones', max_length=13, validators=[apps.core.validators.validate_ecuador_phone], verbose_name='Número de WhatsApp para esta ubicación'),
        ),
        migrations.AlterField(
            model_name='providerprofile',
            name='id_card_back',
            field=apps.core.custom_fields.SmartImageField(blank=True, max_length=255, upload_to='documents/', validators=[apps.core.validators.validate_image_size_5mb], verbose_name='Cédula posterior'),
        ),
        migrations.AlterField(
            model_name='providerprofile',
            name='id_card_front',
            field=apps.core.custom_fields.SmartImageField(blank=True, max_length=255, upload_to='documents/', validators=[apps.core.validators.validate_image_size_5mb], verbose_name='Cédula frontal'),
        ),
        migrations.AlterField(
            model_name='providerprofile',
            name='profile_photo',
            field=apps.core.custom_fields.SmartImageField(blank=True, help_text='Foto de perfil (puede ser comercial)', max_length=255, upload_to='profiles/', validators=[apps.core.validators.validate_image_size_5mb], verbose_name='Foto de Perfil'),
        ),
        migrations.AlterField(
            model_name='providerprofile',
            name='selfie_with_id',
            field=apps.core.custom_fields.SmartImageField(blank=True, help_text='Foto del rostro sosteniendo la cédula de identidad', max_length=255, null=True, upload_to='providers/validation/selfie/', validators=[apps.core.validators.validate_image_size_5mb], verbose_name='Foto Rostro con Cédula'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=apps.core.custom_fields.SmartImageField(blank=True, max_length=255, upload_to='services/', validators=[apps.core.validators.validate_image_size_5mb], verbose_name='Imagen'),
        ),
    ]
