# Generated by Django 5.0.3 on 2025-12-07 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_allow_null_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerprofile',
            name='extracted_id_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='extracted_id_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='extracted_id_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='facial_match_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='rejection_reasons',
            field=models.TextField(blank=True, help_text='JSON con motivos de rechazo', null=True),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='resubmitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='verification_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='providerprofile',
            name='status',
            field=models.CharField(choices=[('created', 'Creado'), ('pending', 'Pendiente'), ('approved', 'Aprobado'), ('rejected', 'Rechazado'), ('resubmitted', 'Re-enviado')], default='created', max_length=20, verbose_name='Estado'),
        ),
    ]
