# Generated by Django 5.0.3 on 2025-12-12 02:08

import apps.core.custom_fields
import apps.core.validators
from django.db import migrations, models


def migrate_images_forward(apps, schema_editor):
    """Copia imágenes existentes del campo 'image' al nuevo campo 'image_1'"""
    Service = apps.get_model('core', 'Service')
    for service in Service.objects.all():
        if service.image:
            service.image_1 = service.image
            service.save(update_fields=['image_1'])


def migrate_images_backward(apps, schema_editor):
    """Revierte la migración copiando de 'image_1' de vuelta a 'image'"""
    Service = apps.get_model('core', 'Service')
    for service in Service.objects.all():
        if service.image_1:
            service.image = service.image_1
            service.save(update_fields=['image'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_providerprofile_extracted_id_expiry_and_more'),
    ]

    operations = [
        # Paso 1: Agregar los nuevos campos (antes de eliminar el viejo)
        migrations.AddField(
            model_name='service',
            name='image_1',
            field=apps.core.custom_fields.SmartImageField(blank=True, max_length=255, null=True, upload_to='services/', validators=[apps.core.validators.validate_image_size_5mb], verbose_name='Imagen 1'),
        ),
        migrations.AddField(
            model_name='service',
            name='image_2',
            field=apps.core.custom_fields.SmartImageField(blank=True, max_length=255, null=True, upload_to='services/', validators=[apps.core.validators.validate_image_size_5mb], verbose_name='Imagen 2'),
        ),
        migrations.AddField(
            model_name='service',
            name='image_3',
            field=apps.core.custom_fields.SmartImageField(blank=True, max_length=255, null=True, upload_to='services/', validators=[apps.core.validators.validate_image_size_5mb], verbose_name='Imagen 3'),
        ),
        
        # Paso 2: Migrar datos (copiar image -> image_1)
        migrations.RunPython(migrate_images_forward, migrate_images_backward),
        
        # Paso 3: Ahora sí eliminar el campo viejo
        migrations.RemoveField(
            model_name='service',
            name='image',
        ),
        
        # Paso 4: Actualizar el campo description
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(help_text='Puede incluir formato HTML básico', verbose_name='Descripción'),
        ),
    ]

