# Generated by Django 5.0.3 on 2026-01-22 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_service_multiple_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='onesignal_player_id',
            field=models.CharField(blank=True, help_text='ID del dispositivo para notificaciones push', max_length=100, null=True, verbose_name='OneSignal Player ID'),
        ),
    ]
