# Generated by Django 5.2.10 on 2026-01-31 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_profile_onesignal_player_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='duration_type',
            field=models.CharField(choices=[('minutes', 'Minutos'), ('hours', 'Horas'), ('days', 'Días'), ('weeks', 'Semanas'), ('months', 'Meses')], default='minutes', max_length=10, verbose_name='Tipo de Duración'),
        ),
        migrations.AddField(
            model_name='service',
            name='duration_value',
            field=models.IntegerField(default=60, verbose_name='Valor de Duración'),
        ),
        migrations.AlterField(
            model_name='service',
            name='duration_minutes',
            field=models.IntegerField(default=60, verbose_name='Duración (minutos)'),
        ),
    ]
