# Generated by Django 5.0.3 on 2025-11-13 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.CharField(help_text='Número de teléfono del destinatario', max_length=50, verbose_name='Destinatario')),
                ('message_type', models.CharField(help_text='Tipo de template: booking_created, booking_accepted, etc.', max_length=50, verbose_name='Tipo de Mensaje')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('sent', 'Enviado'), ('delivered', 'Entregado'), ('read', 'Leído'), ('failed', 'Fallido')], default='pending', max_length=20, verbose_name='Estado')),
                ('response', models.TextField(blank=True, help_text='Respuesta completa de la API de WhatsApp', null=True, verbose_name='Respuesta de API')),
                ('message_id', models.CharField(blank=True, help_text='ID único del mensaje retornado por WhatsApp', max_length=255, null=True, verbose_name='ID del Mensaje')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Mensaje de Error')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Log de WhatsApp',
                'verbose_name_plural': 'Logs de WhatsApp',
                'db_table': 'whatsapp_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'created_at'], name='whatsapp_lo_recipie_7e414a_idx'), models.Index(fields=['status'], name='whatsapp_lo_status_d95a49_idx'), models.Index(fields=['message_type'], name='whatsapp_lo_message_b348fc_idx')],
            },
        ),
    ]
